### ISSUE TITLE
Webpack for AOT can't handle lambda expressions

### ISSUE THREAD

**Issue by ckapilla** [auth0/angular2-jwt#410]
This is for the v1.0 branch -- it is a known issue that lambda expressions won't work when compiling with Webpack for AOT as that process reguires named exported functions.  Thus this line  in jwt.interceptor.ts and jwt.interceptor.d.ts causes an error:

**tokenGetter?: () => string | Promise<string>;**

The error at runtime is  

**this.tokenGetter is not a function.** 

A work-around is to replace the lambda expression with a named exported function. I'm not sure how that would work in a d.ts file, hopefully you can figure that out. Thanks.

**Comment by jjoao07** [comment]
I'm facing
 same problem
Can someone help us please


![screen shot 2017-08-11 at 2 41 05 am](https://user-images.githubusercontent.com/19816874/29197997-72d453b8-7e40-11e7-92ee-072a019ee1d9.png)
![screen shot 2017-08-11 at 2 43 11 am](https://user-images.githubusercontent.com/19816874/29197995-72bc3274-7e40-11e7-9753-566561bb68ca.png)

**Comment by jculverwell** [comment]
I fixed it like this

```
export function getAccessToken() {
  return localStorage.getItem('access_token');
}

```

```
JwtModule.forRoot({
      config: {
        tokenGetter: (getAccessToken),
        whitelistedDomains: ['localhost:44314']
      }
    })
```

**Comment by jjoao07** [comment]
okay cool!

i will check out on morning and let you know, 
if works on my side.

**Comment by jculverwell** [comment]
cool, just remember to change the whitelistedDomains in the example I pasted

**Comment by jjoao07** [comment]
okay cool!

**Comment by ckapilla** [comment]
Thanks for your suggestion -- interesting idea to use a string. Alas I'm still getting this error when I try it:
```
TypeError: this.tokenGetter is not a function
    at JwtInterceptor.intercept (vendor.bundle.js:1)
    at HttpInterceptorHandler.handle (
```

**Comment by rafaelss95** [comment]
@jculverwell's solution didn't work for me either.

@chenkie do you have any solution for this?

**Comment by StefanErakovic** [comment]
This worked ok for me, in same module: 
Before module declaration: 

`export function getJwtToken(): string {
  return localStorage.getItem("access_token");
}`

Module imports config:
`JwtModule.forRoot({
      config: {
        tokenGetter: getJwtToken,
        whitelistedDomains: ['localhost:8000']
      }
    })`

Angular 4.3.6
@auth0/angular-jwt 1.0.0-beta.9

Without a return type declaration the build wasn't passing for me.
