### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined (crashes site on logout)

### ISSUE THREAD

**Issue by gethinoakes** [auth0/angular2-jwt#554]
Hi guys, this issue only occurs when the user is logged out and completely crashes the app. I get a bunch of errors about not being able to read 'split' of undefined.

```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'split' of undefined
    at JwtHelperService.push../node_modules/@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.decodeToken (jwthelper.service.js:70)
    at JwtHelperService.push../node_modules/@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.getTokenExpirationDate (jwthelper.service.js:83)
    at JwtHelperService.push../node_modules/@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.isTokenExpired (jwthelper.service.js:96)
    at AuthService.push../src/app/core/auth/auth.service.ts.AuthService.isLoggedIn (auth.service.ts:124)
```

As I said, this only happens when the user logs out but completely crashed the app so they can't log back in.

Here's how JWT is implemented, it's been this way for a few months and nothing's changed so I have no idea what is going on here.

app.module.ts
```
export function tokenGetter() {
  const user = JSON.parse(localStorage.getItem('user'));
  const userToken = user ? user.token : null;
  return userToken;
}

...

JwtModule.forRoot({
  config: {
    tokenGetter: tokenGetter,
    whitelistedDomains: ['localhost:4200']
  }
}),
```

auth.service.ts
```
import { JwtHelperService } from '@auth0/angular-jwt';

constructor(
    private http: HttpClient,
    private jwtHelper: JwtHelperService
  ) {}

...

isLoggedIn() {
  return this.jwtHelper.isTokenExpired() ? false : true;
}
```

The only way I can get back into the app to log back in is to comment out the return statement within the isLoggedIn function.

Any help would be very much appreciated, thanks.

**Comment by gethinoakes** [comment]
Ok so looking through some other issues and pull requests, it seems that `isTokenExpired()` doesn't handle null (expired) tokens... if I'm right in that assumption then isn't this method completely broken? By it's name it should return false if the token is null and/or expired. It's also not mentioned in the readme anywhere so I assume this is in fact a bug.

#495 seems like it should have fixed this from the description, but for now and for anyone else seeing this issue this is how I fixed it:

```
isLoggedIn() {
    const token = this.user ? (this.user.token ? this.user.token : null) : null;
    return token ? (this.jwtHelper.isTokenExpired() ? false : true) : false;
  }
```

**Comment by gethinoakes** [comment]
Thanks @d-go, that is much cleaner. I look forward to when `isTokenExpired` returns false for null tokens 🙂

**Comment by barrcodes** [comment]
My token appears to decode from raw correctly, but `isTokeExpired` still throws the error outlined above. The decoded token object prototype does not appear to have the `split` method:

```

Object Prototype

__defineGetter__(propertyName, getterFunction)

__defineSetter__(propertyName, setterFunction)

__lookupGetter__(propertyName)

__lookupSetter__(propertyName)

constructor: function()

hasOwnProperty(propertyName)

isPrototypeOf(property)

propertyIsEnumerable(propertyName)

toLocaleString()

toString()

valueOf()
```

**Comment by barrcodes** [comment]
My issue is resolved. I dug through the code of `isTokenExpired` and noticed that it expected an encoded token. I was passing in a decoded token by mistake.
